name: Vars context test
run-name: Vars context test
on:
  workflow_dispatch:
jobs:
  vars-context-test:
    runs-on: ubuntu-latest
    steps:
      - name: Print JOB_NAME
        run: echo "I'm doing ${{ vars.JOB_NAME }}"
